In [1]:
import numpy as np
from sympy import *

## Question 1
Compute the inverse

In [2]:
A = np.array([
    [3,3],
    [-2,-1]
])

print(np.linalg.inv(A))

[[-0.33333333 -1.        ]
 [ 0.66666667  1.        ]]


## Question 2

Find solution to system of equations using matrix inverse


In [13]:
# Coefficents of system 
A = np.array([
    [0,5,-10],
    [1,3,-2],
    [0,4,-7,]
])

# Constants of system
b = np.array([
    [-25,-8,-18]
])

Ainv = np.linalg.inv(A)

# Ax = b -> x = A^-1 b
x = Ainv@b.T

print("A^-1=\n",Ainv)
print("x =\n",x)

A^-1=
 [[ 2.6  1.  -4. ]
 [-1.4  0.   2. ]
 [-0.8  0.   1. ]]
x =
 [[-1.]
 [-1.]
 [ 2.]]


## Question 3

Find A given two other matrices using the inverse

In [12]:
B = np.array([
    [9,0,-7],
    [-6,3,9],
    [2,6,4]
])

C = np.array([
    [0,5,-10],
    [0,3,-9],
    [1,3,1]
])

# WARN: GIVEN EQAUTINO DIFFERENT EACH TIME ### 
# Isolate A, then change print statement to match equation

# B A^-1 = C <-- Given equation
# B = C A <-- multiply both sides by A (A^-1 A = 1)
# C^-1 B = A <-- multiply both sides by C^-1 

print("A =\n", np.linalg.inv(C)@B)

A =
 [[-30.   13.   39. ]
 [  9.4  -2.  -10.2]
 [  3.8  -1.   -4.4]]


## Question 4

Find conditions on k that will make the matrix A invertible.

In [8]:
for k in range(-100,100):   
    A = np.array([
    [2,1,0],
    [-1,k,-2],
    [1,3,2]
    ])  
    if np.linalg.det(A) == 0:
        print(k)
        break
    # Honestly, should never get to this, idk if this actually works if is always invertible. Idk test for if it is never invertbile. 
    if k == 99: 
        print(always)
        break

-3


## Question 5

Find the inevrse of the given transformation, T

In [6]:
T = np.array([
    [5,-10],
    [3,-5]
])

# Include variables in a single vector, i.e., 
# [[x1 + y1]
#  [x2 + y2]]
print(np.linalg.inv(T))

[[-1.   2. ]
 [-0.6  1. ]]
