In [88]:
import numpy as np

## Question 1

 For each of the following elementary matrices, give the row operation that has the same result as left-multiplication by the given matrix

In [89]:
# Pretty easy, no code needed. 
# Identify row operations required to get to given matrix from identity matrix

## Question 2

Find inverse of matrices that are nearly the idenitiy matrix

In [90]:
# Can use to check, but should be able to do without

A = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,0,1], 
    [0,0,1,0]
])

print(np.linalg.inv(A))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


## Question 3

If E, F, G are the following elementary matrices, compute the given matrix expression.

In [91]:
E = np.array([
    [2,0,0,0], # Multiply R_1 by 2
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])

F = np.array([
    [1,0,0,0],
    [0,0,0,1], # Swap rows
    [0,0,1,0],
    [0,1,0,0]  # Swap rows
])

G = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,-3], # Add -3*R_4 to row 3
    [0,0,0,1]
])

Einv, Finv, Ginv = np.linalg.inv([E,F,G])

print("E^-1 = \n", Einv,'\n\nF^-1 =\n',Finv,' \n\nG^-1 =\n',Ginv,'\n ')

# Will have to change this
print('Result = \n', np.linalg.inv((F@Ginv@E@G)))

E^-1 = 
 [[0.5 0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]] 

F^-1 =
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]  

G^-1 =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]] 
 
Result = 
 [[0.5 0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  1.  0. ]
 [0.  1.  0.  0. ]]


## Question 4

Compute the specified power of each of the following elementary matrices

In [92]:
# Apply given power to any number in diagonal
# Multiply any number in off diagonal by power, except 1 (1=1)
# Even powers swap numbers in non zero elements? (I'm not sure here)

## Question 5

Given the following matrices A and B, find an elementary matrix E such that B = EA

Use elementary row operations dictated by an elementary matrix


In [93]:
# Again, can be used to test but not necessary.

A = np.array([
    [2,8,2],
    [-7,-9,1],
    [2,-5,-5],
    [3,-1,-8]
])

E = np.array([
    [1,2,0,0], #  add 2*R_2 to row 1
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])

print(E@A)

[[-12 -10   4]
 [ -7  -9   1]
 [  2  -5  -5]
 [  3  -1  -8]]


## Question 6

Given the following matrices A and B, find elementary matrices E and F such that B = FEA

Use elementary row operations dictated by elementary matrixes

In [94]:
# Same thing as 5, but with more than one elementary matrix

A = np.array([
    [-8,6,7],
    [3,4,-2],
    [-6,-6,0],
    [5,8,1]
])

E = np.array([
    [0,0,1,0], # Swiitch rows
    [0,1,0,0],
    [1,0,0,0], # Switch rows
    [0,0,0,1]
])

F = np.array([
    [1,0,0,0], 
    [0,-2,0,0], # Multiply row 2 by -2
    [0,0,1,0], 
    [0,0,0,1]
])

print(F@E@A)

[[-6 -6  0]
 [-6 -8  4]
 [-8  6  7]
 [ 5  8  1]]


## Question 7

Given the following matrix A, find an invertible matrix U so that UA is equal to the reduced row-echelon form of A

In [98]:
from sympy import *

A = np.array([
    [2,6,-2,-32],
    [-2,-1,-3,7],
    [2,8,-4,-42],
])

# Get number of rows
m = len(A)

# Concatenate identity matrix
Aaug = np.array(np.concatenate((A,np.eye(m,m)),axis=1),dtype='int64')

# Convert to sympy matrix for rref
Aaug = Matrix(Aaug) 
Asol = Aaug.rref() 

# extract matrix from sympy object
Asol = Asol[0] 
# Extract the modified identity matrix
Ainvrref = Asol[:,m+1:]  

# Print whole thing to double check
print('rref(A|I) =\n',np.array(Asol))
print(' ')

# Answer 
print("U = \n",np.array(Ainvrref))

rref(A|I) =
 [[1 0 2 -1 0 -4/7 -1/14]
 [0 1 -1 -5 0 1/7 1/7]
 [0 0 0 0 1 2/7 -5/7]]
 
U = 
 [[0 -4/7 -1/14]
 [0 1/7 1/7]
 [1 2/7 -5/7]]
