In [8]:
import numpy as np
from sympy import *

## Question 1

 Use the ~~cofactor expansion~~ **python**
 to compute the following determinant:

In [2]:
A = np.array([
    [-3,10,-5],
    [10,4,-8],
    [-7,10,10]
])

print(np.linalg.det(A))

-1440.0000000000005


## Question 2

Find a formula in terms of k for the following determinant:

In [5]:
k = Symbol('k')

afj, bgh, cei, hfc, iga, jeb = [], [], [], [], [], []

A = np.array([
    [-1,0,7],
    [k,4,-7],
    [-1,-2,4]
])

# Only works for 3x3 matrices
# Uses the Rule of Sarrus method
def sarrus(A):
    for i in range(3):
        afj.append(A[i][i])
        hfc.append(A[2+(-1*i)][i])

    bgh.append(A[0][1])
    bgh.append(A[1][2])
    bgh.append(A[2][0])

    cei.append(A[0][2])
    cei.append(A[1][0])
    cei.append(A[2][1])

    iga.append(A[2][1])
    iga.append(A[1][2])
    iga.append(A[0][0])

    jeb.append(A[2][2])
    jeb.append(A[1][0])
    jeb.append(A[0][1])


sarrus(A)

# Double checking work
print(afj,bgh,cei,hfc,iga,jeb)

# Shows partial breakdown of A, if A is:
# [a b c]
# [e f g]
# [h i j] 
# afj + bgh + cei - hfc - iga - jeb
print(
    np.prod(afj),'+',np.prod(bgh),'+',np.prod(cei),
    '-',
    np.prod(hfc),'-',np.prod(iga),'-',prod(jeb)
    )

res = np.prod(afj) + np.prod(bgh) + np.prod(cei) - np.prod(hfc) - np.prod(iga) - np.prod(jeb)

print('')
print('det(A) in terms of k =',res)

[-1, 4, 4] [0, -7, -1] [7, k, -2] [-1, 4, 7] [-2, -7, -1] [4, k, 0]
-16 + 0 + -14*k - -28 - -14 - 0

det(A) in terms of k = 26 - 14*k


## Question 3

Let A be a 2×2 (can change) matrix and suppose that det(A)=6 (can cahnge). For each of the following row operations, determine the value of det(B), where B is the matrix obtained by applying that row operation to A (can change).

In [6]:
def operations(det, operation, value=1):
    if operation == 'scale':
        print('Multiplied a row by some scalar: det =',det * value)
    elif operation == 'swap':
        print('Swaped two rows (doesn\'t matter which): det =',-1*det)
    elif operation == 'add':
        print('Added one row to another (does nothing): det =',det)
    else:
        print('Operations accepted: scale (needs value if so, default is 1), swap, and add')
        print('Please try again')

# Needs (Determinant, operation, scalar(only needed if scaling))
operations(6,'scale',3)

operations(6,'swap')

operations(6,'add')

Multiplied a row by some scalar: det = 18
Swaped two rows (doesn't matter which): det = -6
Added one row to another (does nothing): det = 6


In [15]:
a,b,c,d,e,f,g,h,i = symbols('a,b,c,d,e,f,g,h,i')

A = Matrix([
    [a,b,c],
    [d+3*g,e+3*h,f+3*i],
    [g,h,i]
])

A.det()

a*e*i - a*f*h - b*d*i + b*f*g + c*d*h - c*e*g

## Question 4

Compute the determinant of the matrix A, below, by using row operations to transform A to an upper-triangular matrix B. Then express the determinant of A as a multiple k of the determinant of B, and use this to compute the determinant of A.



In [7]:
# I use QR decomposition here to find upper right triangle, R

A = np.array([
    [10,-1,2,8],
    [30,-18,-11,38],
    [0,5,7,-8],
    [-60,51,27,-67]
])

Q,R = np.linalg.qr(A)

print(R)
print(' ')

# Finding an ref is simpler, but typing numbers in isn't that
# hard... but it works! 
# I think QR decomp uses rref, hence weird results.
print('det(R) =',np.round(np.linalg.det(R)))
print('det(A) =',np.round(np.linalg.det(A)))
print('k =',np.round(np.linalg.det(R))/np.round(np.linalg.det(A)))


[[-67.82329983  53.22654617  28.45629754 -77.25958503]
 [  0.         -10.8597782   -8.59774145   3.38304611]
 [  0.           0.          -4.39522154   8.96239353]
 [  0.           0.           0.           0.43246144]]
 
det(R) = -1400.0
det(A) = 1400.0
k = -1.0


## Question 5

If the determinant of the first matrix below is as given, find the determinant of the other matrix.

In [6]:
# Basically the same as question 3, but harder to tell what operations were used.

# Means we can use function. Must run cell above containing the
# function in order to make it work.
operations(-5,'swap')

# Take given det, apply function again
operations(5,'add')

operations(5,'scale',6)

Swaped two rows (doesn't matter which): det = 5
Added one row to another (does nothing): det = 5
Multiplied a row by some scalar: det = 30
