In [1]:
import numpy as np
from sympy import *

## 3.2 Question 1

  If A, B, and C are 3×3 matrices; and det(A) = 5, det(B) = −2, and det(C) = −1 then compute:

$det(4C^TA^TC^2B^3C^TB^{-1})$ 
 


In [2]:
# Determinants of given matrices
A, B, C = 5,-2,-1

# Size of given matrices
n = 3

# Given computation, ** = ^
print(
    4**n * C * A * C**2 * B**3 * C * B**-1
)

1280.0


## 3.2 Question 2

Compute the adjugate of the following matrix:


In [3]:
A = np.array([
    [7,0,5],
    [4,4,-6],
    [6,-6,-6]
])

# Adj(A) = A^-1 * det(A) --- Only for square matrices
print(np.linalg.inv(A)*np.linalg.det(A))

[[-60. -30. -20.]
 [-12. -72.  62.]
 [-48.  42.  28.]]


## 3.3 Question 1

Find the characteristic polynomial of A. Use x for the variable in your polynomial. You do not need to factor your polynomial.


In [4]:
x = symbols('x')

# Subtract x from diagonal elements
A = Matrix([
    [0-x,-0,-2],
    [1,2-x,1],
    [1,0,3-x]
])

real_roots(A.det())

[1, 2, 2]

In [5]:
A = np.array([
    [0,0,-2],
    [1,2,1],
    [1,0,3]
])

v = np.array([-2,1,1]).T

print(A@v)


[-2  1  1]


## 3.3 Question 2

Find the characteristic polynomial of A. Use x for the variable in your polynomial.


In [6]:
A = Matrix([
    [-3-x,0,-3,4],
    [0,-3-x,3,-1],
    [0,0,0-x,-1],
    [0,0,0,2-x]
])

A.det()

x**4 + 4*x**3 - 3*x**2 - 18*x

## 3.3 Question 3

List all of the distinct eigenvalues of A. Enter your answer as a list of numbers separated by commas.

In [7]:
A = np.array([
    [5,1],
    [0,5]
])

print(np.linalg.eigvals(A))

[5. 5.]


## 3.3 Question 4

List all of the distinct eigenvalues of A. Enter your answer as a list of numbers separated by commas.


In [8]:
A = np.array([
    [1,-1,0],
    [0,0,0],
    [0,-2,-2]
])

print(np.linalg.eigvals(A))

[ 1. -2.  0.]


## 3.3 Question 5

Find the basic eigenvectors of A corresponding to the eigenvalue λ.

In [14]:
A = np.array([
    [0,0,-2],
    [1,2,1],
    [1,0,3]
])

evals,evecs = np.linalg.eig(A)
evals = evals.astype(int)

print('Eigen values ↓\n')
print(evals)
print(' ')
print('Eigen vectors (normalized) ↓\n')
print(evecs)

print('\n-------------------\n')

A = Matrix(A)
sym_evecs = A.eigenvects()

for i in range(len(sym_evecs)):
    print('Eigenvalue:',sym_evecs[i][0])
    print('Eigenvector(s)↓\n')
    print(np.array(sym_evecs[i][2]))
    print(' ')

print('-------------------\n')
# Change based on eigen value value of interest
λ = int(2) 

print('Eigenvector(s) of given eigenvalue,',λ,' ↓ \n')
for i in range(len(sym_evecs)):
    if sym_evecs[i][0] == λ:
            print(np.array(sym_evecs[i][2][:]))

Eigen values ↓

[2 1 2]
 
Eigen vectors (normalized) ↓

[[ 0.         -0.81649658  0.70710678]
 [ 1.          0.40824829  0.        ]
 [ 0.          0.40824829 -0.70710678]]

-------------------

Eigenvalue: 1
Eigenvector(s)↓

[[[-2]
  [1]
  [1]]]
 
Eigenvalue: 2
Eigenvector(s)↓

[[[0]
  [1]
  [0]]

 [[-1]
  [0]
  [1]]]
 
-------------------

Eigenvector(s) of given eigenvalue, 2  ↓ 

[[[0]
  [1]
  [0]]

 [[-1]
  [0]
  [1]]]


In [18]:
A = np.array(A,dtype='float')
v = np.array([-2,1,1]).T
D = np.diag([1,1,1])

print((A - D)@v)


[0. 0. 0.]


## 3.3 Question 6

Find all distinct eigenvalues of A. Then find the basic eigenvectors of A corresponding to each eigenvalue.
For each eigenvalue, specify the number of basic eigenvectors corresponding to that eigenvalue, then enter the eigenvalue followed by the basic eigenvectors corresponding to that eigenvalue.


In [11]:
A = np.array([
    [-9,12],
    [-6,9]
])

evals,evecs = np.linalg.eig(A)
evals = evals.astype(int)

print('Eigen values ↓\n')
print(evals)
print(' ')
print('Eigen vectors (normalized) ↓\n')
print(evecs)

print('\n-------------------\n')

A = Matrix(A)
sym_evecs = A.eigenvects()

for i in range(len(sym_evecs)):
    print('Eigenvalue:',sym_evecs[i][0])
    print('Eigenvector(s)↓\n')
    print(np.array(sym_evecs[i][2]))
    print(' ')

Eigen values ↓

[-3  3]
 
Eigen vectors (normalized) ↓

[[-0.89442719 -0.70710678]
 [-0.4472136  -0.70710678]]

-------------------

Eigenvalue: -3
Eigenvector(s)↓

[[[2]
  [1]]]
 
Eigenvalue: 3
Eigenvector(s)↓

[[[1]
  [1]]]
 


## 3.3 Question 7 

Find an invertible matrix P and a diagonal matrix D such that $P^{−1}AP=D$.


In [12]:
A = np.array([
    [-9,5,-2],
    [-12,7,-4],
    [6,-3,3]
])

# eigendecomposition
evals,evecs = np.linalg.eig(A)

print('D =')
print(np.diag(evals.astype(int)))
print(' ')

A = Matrix(A)
sym_evecs = A.eigenvects()

for i in range(len(sym_evecs)):
    print('Eigenvalue:',sym_evecs[i][0])
    print('Eigenvector(s)↓\n')
    print(np.array(sym_evecs[i][2]))
    print(' ')

print('P = all eigenvectors in matrix')


D =
[[-3  0  0]
 [ 0  3  0]
 [ 0  0  1]]
 
Eigenvalue: -3
Eigenvector(s)↓

[[[-2]
  [-2]
  [1]]]
 
Eigenvalue: 1
Eigenvector(s)↓

[[[1/2]
  [1]
  [0]]]
 
Eigenvalue: 3
Eigenvector(s)↓

[[[-1]
  [-2]
  [1]]]
 
P = all eigenvectors in matrix
