In [3]:
import numpy as np
from sympy import *
from fractions import Fraction
from scipy.linalg import null_space

## Question 1

Let A be the matrix given below. Find an example of each the following: 

In [4]:
A = np.array([
    [1,-4,-1,-2,2,-4],
    [1,-4,2,4,-1,5],
    [-2,8,0,2,-6,8],
    [-1,4,2,2,3,-1],
    [-1,4,3,3,3,0]
])

print(A.shape,'\n')

print('Nonzero vector in im(A) that is not already a column in A')
a = np.array([np.sum(A,axis=1)]).T
print(a,'\n')
print('Most random vectors should not be in im(A)')
print(np.array([np.random.randint(-10,10,size=A.shape[0])]).T,'\n')

# Possilbe null space of A
c = np.array(Matrix(A).nullspace()[0])
print('Vector in nullspace of A')
print(c)

(5, 6) 

Nonzero vector in im(A) that is not already a column in A
[[-8]
 [ 7]
 [10]
 [ 9]
 [12]] 

Most random vectors should not be in im(A)
[[ -9]
 [  3]
 [-10]
 [ -9]
 [ -4]] 

Vector in nullspace of A
[[4]
 [1]
 [0]
 [0]
 [0]
 [0]]


## Question 2 

For each of the following vectors, determine whether the vector is in the image of A. If so, demonstrate this by providing a vector x so that Ax=bi.

In [5]:
A = np.array([
    [2,-4,-4],
    [1,0,-6],
    [1,0,-1],
    [2,-7,3]
])

b1 = np.array([[-7,-1,-4,-2]]).T
b2 = np.array([[-6,-5,0,-2]]).T
b3 = np.array([[-12,-2,-2,-18]]).T

A1 = Matrix(np.concatenate((A,b1),axis=1))
A2 = Matrix(np.concatenate((A,b2),axis=1))
A3 = Matrix(np.concatenate((A,b3),axis=1))

print(np.array(Matrix(A).rref()[0]),'\n')
print(np.array(A1.rref()[0]),'\n')
print(np.array(A2.rref()[0]),'\n')
print(np.array(A3.rref()[0]),'\n')

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]] 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

[[1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 0]] 

[[1 0 0 -2]
 [0 1 0 2]
 [0 0 1 0]
 [0 0 0 0]] 



## Question 3
For each of the following vectors, determine whether it is in the image and/or null space of A. If the vector is in the image of A find a vector x so that Ax=vi

In [6]:
A = np.array([
    [3,6,9],
    [-2,-4,-6],
    [1,3,4]
])

v1 = np.array([[3,-2,3]]).T
v2 = np.array([[-1,-1,1]]).T

A1 = Matrix(np.concatenate((A,v1),axis=1))
A2 = Matrix(np.concatenate((A,v2),axis=1))

print(np.array(A1.rref()[0]),'\n')
print(A@v1)
print('\n-------\n')
print(np.array(A2.rref()[0]),'\n')
print(A@v2)

[[1 0 1 -3]
 [0 1 1 2]
 [0 0 0 0]] 

[[ 24]
 [-16]
 [  9]]

-------

[[1 0 1 0]
 [0 1 1 0]
 [0 0 0 1]] 

[[0]
 [0]
 [0]]


## Question 4

For each of the following vectors, determine whether it is in span{a, b, c}. If so, express it as a linear combination using a, b, and c as the names of the vectors above.

In [7]:
A = np.array([
    [2,6,-2],
    [-2,-4,0],
    [3,10,-2],
    [1,6,-3]
])

v1 = np.array([[-16,10,-25,-16]]).T
v2 = np.array([[-5,-2,-8,8]]).T
v3 = np.array([[-8,6,-15,-8]]).T

A1 = Matrix(np.concatenate((A,v1),axis=1))
A2 = Matrix(np.concatenate((A,v2),axis=1))
A3 = Matrix(np.concatenate((A,v3),axis=1))

# print(np.array(Matrix(A).rref()[0]),'\n')
print(np.array(A1.rref()[0]),'\n')
print(np.array(A2.rref()[0]),'\n')
print(np.array(A3.rref()[0]),'\n')


[[1 0 0 -1]
 [0 1 0 -2]
 [0 0 1 1]
 [0 0 0 0]] 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

[[1 0 0 1]
 [0 1 0 -2]
 [0 0 1 -1]
 [0 0 0 0]] 



## Question 5

Given the following vectors u and v, find a vector w in ℝ3 so that {u, v, w} spans ℝ3 and a non-zero vector z in ℝ3 so that {u, v, z} does not span ℝ3.

In [8]:
u = np.array([8,10,10])
v = np.array([9,-4,-8])

w = np.cross(u,v)
z = u+v

print(np.array([w]).T,'\n ')
print(np.array([z]).T)


[[ -40]
 [ 154]
 [-122]] 
 
[[17]
 [ 6]
 [ 2]]


## Question 6 

Determine all values of k for which the following set of vectors spans ℝ4. You can select 'always', 'never', 'k = ', or 'k ≠', then specify a value or comma-separated list of values.

In [9]:
k = symbols('k')

A = Matrix([
    [1,0,0,2],
    [1,1,0,0],
    [0,0,-2,0],
    [0,4,6,k]
])


A.echelon_form()

Matrix([
[1, 0,  0,         2],
[0, 1,  0,        -2],
[0, 0, -2,         0],
[0, 0,  0, -2*k - 16]])

In [10]:
# Solve for when k = 0
solve(A.echelon_form()[-1,-1])[0]

-8

## Question 7

Give a set of vectors that spans each of im(A) and null(A).

In [11]:
A = Matrix([
    [1,1,-1,-7,6],
    [-1,0,0,2,0],
    [-3,0,1,10,-4]
])

Cspace = A.columnspace()
Nspace = A.nullspace()

print('Vectors spanning column space')
for i in range(len(Cspace)):
    print(np.array(Cspace[i]),'\n')

print('Vectors spanning null space')
for i in range(len(Nspace)):
    print(np.array(Nspace[i]),'\n')




Vectors spanning column space
[[1]
 [-1]
 [-3]] 

[[1]
 [0]
 [0]] 

[[-1]
 [0]
 [1]] 

Vectors spanning null space
[[2]
 [1]
 [-4]
 [1]
 [0]] 

[[0]
 [-2]
 [4]
 [0]
 [1]] 

