In [2]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [3]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(4,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[ 2.25233838 -0.13009994 -0.83346301  0.67198549  1.54724722]
 [ 0.56453664  0.72394576 -0.23668359 -0.46701518 -1.04837582]
 [-1.01081597 -0.38514792 -0.45030101 -0.64328299  2.17698677]
 [-0.45589683 -0.47892496  0.47500161 -0.078508   -0.51358343]
 [ 0.75936164 -0.73246071  0.68335829 -0.16791855  0.25291615]]
 
[[ 0.67132     0.2860495 ]
 [ 0.373048   -0.80651901]
 [ 0.42062892  0.31782866]
 [ 0.50664305  0.86663881]
 [ 1.93347033  0.65998893]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[ 0.42450926  0.          0.          0.          0.        ]
 [-1.28333014  0.87606438  0.          0.          0.        ]
 [ 0.69125555  0.35097191  0.14649183  0.          0.        ]
 [-1.36265645 -0.3394134   0.00980883  0.58252251  0.        ]
 [ 0.64638355 -1.36202177  1.9614332  -0.21562696  0.90568654]]
 
[[-0.31393592  1.74505586 -0.29074925 -1.07859333  0.03008


---
# VIDEO: Matrix addition and subtraction
---


In [3]:

# create random matrices
A = np.round(np.random.randn(2,2))
B = np.round(np.random.randn(2,2))
C = np.round(np.random.randn(2,2))

# try to add them
# A+B
A+C



# "shifting" a matrix
l = 23 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

[[ 0.07750587  0.07446618  1.07585865  1.69913408 -0.47180239]
 [ 1.17126061  1.38445814  0.41921586 -0.93142656 -1.85059947]
 [-0.15173269  0.16818307  0.63310615 -0.31305661  1.28960705]
 [ 0.90175407  0.97718882 -1.86195469  0.62735069 -0.1992067 ]
 [-2.48342675  0.87540086  0.76149126  0.12250908 -0.10380067]]
 
[[23.07750587  0.07446618  1.07585865  1.69913408 -0.47180239]
 [ 1.17126061 24.38445814  0.41921586 -0.93142656 -1.85059947]
 [-0.15173269  0.16818307 23.63310615 -0.31305661  1.28960705]
 [ 0.90175407  0.97718882 -1.86195469 23.62735069 -0.1992067 ]
 [-2.48342675  0.87540086  0.76149126  0.12250908 22.89619933]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [2]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


In [15]:
# code challenge: l(A+B) =? sA + sB

m,n = 5,6
A = np.random.randn(n,m)
B = np.random.randn(n,m)

l = np.random.randn()

res1 = l * (A + B)
res2 = l * A + l * B

print(res1 == res2)

# nope! 


[[ 0.00000000e+00  0.00000000e+00 -6.50521303e-19  0.00000000e+00
  -2.77555756e-17]
 [ 0.00000000e+00  1.38777878e-17  0.00000000e+00  0.00000000e+00
  -1.11022302e-16]
 [ 0.00000000e+00  2.77555756e-17  0.00000000e+00  2.77555756e-17
   1.73472348e-17]
 [ 0.00000000e+00  6.93889390e-18  5.55111512e-17  5.55111512e-17
   1.38777878e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.77555756e-17
  -8.67361738e-19]
 [-5.55111512e-17  0.00000000e+00  1.04083409e-17  0.00000000e+00
   0.00000000e+00]]


# VIDEO: Transpose

In [ ]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

In [ ]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!



---
# VIDEO: Diagonal and trace
---


In [ ]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)


---
# VIDEO: Broadcasting matrix arithmetic
---


In [ ]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

In [ ]:
# broadcast on the rows
# print(A+r), print(' ')

# broadcast on the columns
print(A+c)
# print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors
