In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# VIDEO: Computing rank: theory and practice
---


In [3]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank = ' + str(ra))

# set last column to be repeat of penultimate column
B = A
B[:,-1] = B[:,-2]

rb = np.linalg.matrix_rank(B)
# print('rank = ' + str(rb))

rank = 4


In [4]:
A = np.array([[1,3,3],[5,-7,-7],[-5,2,2]])
print(np.linalg.matrix_rank(A))

2


In [3]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4


In [4]:
m = 10
n = 10
r = 5

A = np.round( np.random.randn(m,r) )
B = np.round( np.random.randn(r,n) )

C = A@B

rank = str(np.linalg.matrix_rank(C))

print(np.shape(C))
print(rank)
print(C)


(10, 10)
5
[[ 1.  0. -1.  0.  2.  1.  0.  0.  1.  1.]
 [-1. -2.  0. -2. -2. -1.  0. -2. -2. -1.]
 [-1. -2. -2. -2.  3.  4.  2. -1.  1.  2.]
 [ 2. -2. -5.  4.  7.  3.  2.  1.  2.  1.]
 [-1. -2. -2.  3.  3.  1.  0.  1.  1. -3.]
 [-3.  0.  1.  0. -1.  2.  2.  1.  0.  0.]
 [ 2.  1.  1. -1. -2. -3. -2. -1. -1.  0.]
 [-1. -2. -2.  1.  2.  2.  2.  0.  0.  0.]
 [-1.  1.  1. -1.  2.  2. -2.  1.  3. -1.]
 [ 1.  4.  3.  1. -2. -2. -2.  2.  1.  0.]]



---
# VIDEO: Rank of A^TA and AA^T
---


In [7]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = A.T@A
AAt = A@A.T

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))


AtA: 3x3, rank=3
AAt: 14x14, rank=3


In [9]:
# matrix sizes
m = 2
n = 5

# create matrices
A,B = np.round( 10*np.random.randn(m,n) )

print(A,B)

[-10.  -5.  -6.   5.  -0.] [ 4.  7.  0. 14. -0.]



---
# VIDEO: Making a matrix full-rank by "shifting"
---


In [6]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*A.T@A )

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))


rank(w/o shift) = 29
rank(with shift) = 30
