# 2.2 &mdash; Matrix-Vector Multiplication

In [3]:
import numpy as np
from sympy import *

In [4]:
# Question 1
# No useful code for this, see subsection titled: Elementary Operations (System of Linear Equations)

In [5]:
# Question 2
# No useful code for this...
# Number of unrestired columns = number of parameters; 
# Number of rows = base + number of parametrs;
# unrestired columns get a 1 in the row immediately below last equation that contains a number;
# first column (i.e., + b) = contant matrix;
# s,t columns = -1 * numbers in these columns;
# rows of zeros = reduce number of variables (rows)

In [8]:
# Question 3
# Solve 👏 The 👏 System 👏

# RREF calculator set up

# Make a matrix using the sympy package. 
# Must be a list of lists, i.e., 

# [[],[],[],[]] or ...

# [[x_11,x_12,...,x_1n],
#  [x_21,x_22,...,x_2n],
#        [...],
#  [x_m1,x_m2,...,x_mn]]

# Each list is a row vector of the matrix in question, 
# where number of lists = number of columns
A = Matrix([
            [3,-6,-9,-21],
            [-1,3,4,8],
            [-1,1,3,6]
])

# Compute RREF
rrefA = A.rref()

# Print it out nicely
print('RREF of Matrix A:\n')
print(np.array(rrefA[0]))

RREF of Matrix A:

[[1 0 0 -5]
 [0 1 0 1]
 [0 0 1 0]]


In [9]:
# Question 4
# Combination of Q3 and Q2

A = Matrix([
            [1,5,-2,4],
            [-1,-5,2,-4],
            [2,10,-4,8]
])

# Compute RREF
rrefA = A.rref()

# Print it out nicely
print('RREF of Matrix A:\n')
print(np.array(rrefA[0]))

RREF of Matrix A:

[[1 5 -2 4]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
# Question 5
# No solution, give RREF

A = Matrix([
            [1,2,3,-3],
            [-2,-4,-6,9],
            [-3,-5,-6,10]
])

# Compute RREF
rrefA = A.rref()

# Print it out nicely
print('RREF of Matrix A:\n')
print(np.array(rrefA[0]))

RREF of Matrix A:

[[1 0 -3 0]
 [0 1 3 0]
 [0 0 0 1]]


In [24]:
# Question 6
# Easy af, input matrix and vector

# matrix
A = np.array([
    [9,-5],
    [6,-6],
    [0,-3]
])

# vector (really 2x1 matrix)
v = np.array([-8,3])

# @ = matrix multiplcation operator (dot product)
print(A@v)
print(np.dot(A,v))

# Do unequal sizes work? 

# v2= v = np.array([2,7,3])
# print(A*v2)

[-87 -66  -9]
[-87 -66  -9]


In [27]:
# Question 7 
# Larger version of 6, just as easy! 

# matrix (3x4)
A = np.array([
    [7,6,-6],
    [-10,-2,-10],
    [1,-7,-4],
    [8,9,-3]
])

# vector (really 3x1 matrix)
v = np.array([2,1,7])

# @ = matrix multiplcation operator (dot product)
print(A@v)
print(np.dot(A,v))

[-22 -92 -33   4]
[-22 -92 -33   4]


In [37]:
# Question 8

# I guess yo can find the linear transformation by finding the dot product?

A = np.array([
    [4,5],
    [3,3],
    [-4,3],
])

u = np.array([3,-5])

# enter result as a column matrix
print(A@u)

[-13  -6 -27]
