In [28]:
import numpy as np
from sympy import *
# from fractions import Fraction
# np.set_printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())})

## Question 1

Find a formula for T(x), where x is any vector in ℝ2

In [29]:
Te1 = [-10,-4]
Te2 = [8,-4]
Te3 = [-8,1] # If in ℝ2, then put 0s here

Tx,Ty,Tz = [],[],[]

for i in Te1:
    Tx.append(str(i)+'x')
for i in Te2:
    Ty.append(str(i)+'y')
for i in Te3:
    Tz.append(str(i)+'z')

Txy = np.array([Tx,Ty,Tz])

 # Ignore zeros if in ℝ2
 # Result should be a vector with elements of each row added together. 
print(Txy.T)
# E.g.,
# T[xyz] = [-10x-8y-8z, -4x-4y+z]


[['-10x' '8y' '-8z']
 ['-4x' '-4y' '1z']]


## Question 2

Suppose T: ℝ3→ℝ2 is a linear transformation. Let u and v be the vectors given below, and suppose that T(u) and T(v) are as given. Find given transformation.

In [30]:
Tu = np.array([[-1,2]])
Tv = np.array([[-15,18]])

# This needs to match T(x*u (+-) y*v) given
T = -1*Tu+3*Tv

print(T.T)


[[-44]
 [ 52]]


## Question 3

Suppose T: ℝ3→ℝ2 is a linear transformation. Let u, v and w be the vectors given below, and suppose that T(u) and T(v) are as given. Find T(w)

In [31]:
u = np.array([[2,-3]]).T
v = np.array([[2,-2]]).T
w = np.array([[8,-9]]).T

# Turn vectors into matrix, rref, then extract solution (i.e., the scalars needed to make w from u and v)
uvw = Matrix(np.concatenate((u,v,w),axis=1)).rref()
scalars = np.array(uvw[0])[:,2:]

print('Scalars = ')
print(scalars,'\n')

Tu = np.array([[15,-13,-19]]).T
Tv = np.array([[12,-10,-14]]).T

# Test scalars
k = scalars[0][0]
l = scalars[1][0]

T = k*u + l*v

print('w = k*u + l*v')
print(T,'\n')

print("Does k*u + l*v = w?")
print(w==T,'\n')

Tw = k*Tu + l*Tv

print('T(w) =')
print(Tw)

Scalars = 
[[1]
 [3]] 

w = k*u + l*v
[[8]
 [-9]] 

Does k*u + l*v = w?
[[ True]
 [ True]] 

T(w) =
[[51]
 [-43]
 [-61]]


## Question 4

Let A be the matrix below and define a transformation T:ℝ3→ℝ3 by T(u) = Au. For the vector b below, find a vector u such that T maps u to b, if possible. Otherwise state that there is no such u.

In [32]:
A = np.array([
    [3,6,3],
    [-3,-3,-9],
    [-1,1,-6]
])

b = np.array([[-6,-18,-19]]).T

# Similar to question 3, create augmented matrix in order 
# to find vector u, which describes transformation needed 
Ab = Matrix(np.concatenate((A,b),axis=1)).rref()
u = np.array(Ab[0])[:,3:]

print(u)

[[-1]
 [-2]
 [3]]



## Question 5

Let A be the matrix below and define a transformation T:ℝ3→ℝ3 by T(u) = Au. For the vector b below, find a vector u such that T maps u to b, if possible. Otherwise state that there is no such u.



In [33]:
A = np.array([
    [0,3,3],
    [0,1,1],
    [1,-3,0]
])

b = np.array([[3,1,-3]]).T

# Similar to question 3, create augmented matrix in order 
# to find vector u, which describes transformation needed 
Ab = Matrix(np.concatenate((A,b),axis=1)).rref()
u = np.array(Ab[0])[:,3:]

print(u)

[[0]
 [1]
 [0]]


## Question 6

Suppose T is a transformation from ℝ2 to ℝ2. Find the matrix A that induces T if T is rotation by given θ.

In [34]:
import math

# Given angle can change 
θ = 2/3 * math.pi

A = np.array([
    [math.cos(θ), -1* math.sin(θ)],
    [math.sin(θ), math.cos(θ)]
])

print(A)

[[-0.5       -0.8660254]
 [ 0.8660254 -0.5      ]]
