In [1]:
import numpy as np
from sympy import *

## Question 1

If **u** and **v** are the vectors below, solve the following equation for the vector **x**.

Given equation:
$$ 
\begin{align*}
3(\vec{x}-3\vec{u})-2\vec{v}=2\vec{v}+\vec{u}-\vec{x}
\end{align*}
$$

In [2]:
from fractions import Fraction
np.set_printoptions(formatter={'all':lambda x: str(Fraction(x).limit_denominator())})

u,v,x = symbols('u,v,x')

# Given equation -> Eq(left side, right side)
vec_eq = Eq(3*(x-3*u)-2*v, 2*v+u-x)
print(solve(vec_eq, x))
print(' ')

# Given vectors
u = np.array([[-4,3,-3]]).T
v = np.array([[5,-2,1]]).T

# Result from solve() function
x = (5/2)*u + v

print(x)


[5*u/2 + v]
 
[[-5]
 [11/2]
 [-13/2]]


## Question 2

Find the distance d between the points $P_1$ and $P_2$ by first finding the vector $\vec{v}$ from $P_1$ to $P_2$, then finding the length of $\vec{v}$. Use the square root symbol '√' where needed to give an exact value for your answer.



In [3]:
# Inputing as row vector (easeir), tranpose to make column vector
P1 = np.array([[-9,-8,1]]).T
P2 = np.array([[-7,4,4]]).T

# v = distance between points
v = P2-P1
print(f'v = {v.T[0]}.T\n')

# d = norm = length = ||v|| = (v.T@v)**0.5 = sqrt(v.T@v)
d = np.linalg.norm(v)
vTv = v.T @ v

print(f'd = sqrt({int(d**2)})\n')
print('d =', d)
print('d^2 =', int(d**2))
print('vTv =', vTv[0][0])



v = [2 12 3].T

d = sqrt(157)

d = 12.529964086141668
d^2 = 157
vTv = 157


## Question 3

Find a unit vector $\vec{u}$ with the same direction as the given vector $\vec{v}$. Use the square root symbol '√' where needed to give an exact value for your answer. 

In [4]:
v = np.array([[-9,5,10]]).T

u = v/np.linalg.norm(v)
vhat = v / (v**2).sum()**0.5

# u = vhat
print(u-vhat)
print(' ')

print(f'u= sqrt(\n{u**2})\n')
print(f'u=\n{u}')

[[0]
 [0]
 [0]]
 
u= sqrt(
[[81/206]
 [25/206]
 [50/103]])

u=
[[-622923/993403]
 [347451/997372]
 [596331/855896]]


## Question 4

Find the vector equation for the line passing through the points $P_1$ and $P_2$.

In [5]:
p1 = np.array([[-5,-9,7]]).T
p2 = np.array([[-11,-5,9]]).T

v = p2-p1
print(f't =\n{v}\n')

print('Use either p1 or p2 for vector in vector equation')

t =
[[-6]
 [4]
 [2]]

Use either p1 or p2 for vector in vector equation


## Question 5

Find the vector equation for the line passing through the point $P$ and parallel to the line given

---

Code isn't helpful for this one.

1. Input P as a vector
2. Then input all scalrs of t as a vector for the equation

E.g.,

$P(-2,4,6)$ parallel to line 

$$
\begin{align*}
x &= -3+2t \\
y &= 2-8t \\ 
z &= -6+2t 
\end{align*}
$$
yields
$$
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = 
\begin{bmatrix} -2 \\ 4 \\ 6 \end{bmatrix} + 
t \begin{bmatrix} 2 \\ -8 \\ 2 \end{bmatrix}
$$



## Question 6


Let $L_1$ be the line passing through the points $Q_1(5, 3, -4)$ and $Q_2(7,0,−5)$ and let $L_2$ be the line passing through the point $P_1(−32, −13,31)$ with direction vector $d=[−9, −6, 9]^T$ Determine whether $L_1$ and $L_2$ intersect. If so, find the point of intersection $Q$.


In [ ]:
q1 = np.array([[5,3,-4]]).T
q2 = np.array([[7,0,-5]]).T
tvec = q2 - q1

print(f'Direction vector t =\n{tvec}\n')

p1 = np.array([[-32,-13,31]]).T
rvec = np.array([[-9,-6,9]]).T

print(f'Dirction vector r =\n{rvec}\n')

A = Matrix(np.concatenate((tvec,rvec,p1-q1),axis=1))

print(f'A = \n{np.array(A,dtype=float)}\n')

Asol = A.rref()

print(f'rref(A) = \n{np.array(Asol[0],dtype=float)}\n')


t = float(Asol[0][0,2])
r = float(Asol[0][1,2])

print(f't = {str(Fraction(t).limit_denominator())}')
print(f'r = {str(Fraction(r).limit_denominator())}')

Q = Matrix([np.concatenate((q1,tvec*t),axis=1).sum(axis=1)]).T

Q

Direction vector t =
[[2]
 [-3]
 [-1]]

Dirction vector r =
[[-9]
 [-6]
 [9]]

A = 
[[2 -9 -37]
 [-3 -6 -16]
 [-1 9 35]]

rref(A) = 
[[1 0 -2]
 [0 1 11/3]
 [0 0 0]]

t = -2
r = 11/3


Matrix([
[ 1.0],
[ 9.0],
[-2.0]])

### Question 6 Visualized

$$
L_1 = \begin{bmatrix} x \\ y \\ z \end{bmatrix} = 
\begin{bmatrix} 5 \\ 3 \\ -4 \end{bmatrix} + 
t \begin{bmatrix} 2 \\ -3 \\ -1 \end{bmatrix}
$$

$$\downarrow$$

$$
\begin{align*}
x &= 5+2t \\
y &= 3-3t \\ 
z &= -4-t 
\end{align*}
$$

$$\downarrow$$

$$
L_2 = 
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = 
\begin{bmatrix} -32 \\ -13 \\ 31 \end{bmatrix} + 
r \begin{bmatrix} -9 \\ -6 \\ 9 \end{bmatrix}
$$

$$\downarrow$$

$$
\begin{align*}
x &= -32-9r \\
y &= -13-6r \\ 
z &= 31+9r 
\end{align*}
$$

$$\downarrow$$

$$
\begin{align*}
5+2t  &= -32-9r \\
3-3t &= -13-6r \\ 
-4-t &= 31+9r 
\end{align*}
$$

$$\downarrow$$

$$
\begin{align*}
2t-9r &= -37 \\
-3t-6r &= -16 \\ 
-1t+9r &= 35 
\end{align*}
$$

$$\downarrow$$

$$
\operatorname{rref}\left(\begin{bmatrix} 
2 & -9 & -37 \\ 
-3 & -6 & -16 \\ 
-1 & 9 & 35
\end{bmatrix}\right)
$$


In [ ]:
A.rref()[0]

Matrix([
[1, 0,   -2],
[0, 1, 11/3],
[0, 0,    0]])

Input t, or r, back into respective equation (I am using t)
$$
\begin{align*}
x &= 5+2(-2) \\
y &= 3-3(-2) \\ 
z &= -4-(-2) 
\end{align*}
$$
Gives us point of intersect, Q:
$$
\begin{bmatrix} 1 & 9 & -2 \end{bmatrix} 
$$