In [1]:
import numpy as np
from sympy import *
from fractions import Fraction

## Question 1

For each of the following sets of vectors, determine whether it is linearly independent or linearly dependent. If it is dependent, give a non-trivial linear combination of the vectors yielding the zero vector. Give your combination as an expression using u, v, and w for the vector variables **u**, **v**, and **w**.

In [2]:
def linearDependence(a,b,c):
    print('-'*30)
    a = np.array([a])
    b = np.array([b])
    c = np.array([c])

    u,v,w = symbols('u,v,w')
    symbolic = np.array([u,v,w])

    A = np.concatenate((a,b,c))
    print(A)
    print('  rref 🠗')
    print(np.array(Matrix(A).rref()[0]))
    # check leftnullspace for linear dependence
    # return vector required to reach zero vector if true
    ANul = np.array(Matrix(A.T).nullspace())
    if len(ANul) >= 1:
        cokernel = ANul[0].T[0]
        print(f'\nleft nullspace = {cokernel}')
        print(f'\n{symbolic@cokernel} = 0')
        print('-'*30)
    else:
        print('\nVectors are linearly independent')
        print('-'*30)


linearDependence(
    [1,-3,1],
    [-2,6,-1],
    [-3,9,-1],
)
linearDependence(
    [1,3,-3],
    [1,4,2],
    [1,4,-1],
)

------------------------------
[[ 1 -3  1]
 [-2  6 -1]
 [-3  9 -1]]
  rref 🠗
[[1 -3 0]
 [0 0 1]
 [0 0 0]]

left nullspace = [-1 -2 1]

-u - 2*v + w = 0
------------------------------
------------------------------
[[ 1  3 -3]
 [ 1  4  2]
 [ 1  4 -1]]
  rref 🠗
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Vectors are linearly independent
------------------------------


## Question 2 

Given the following vectors u and v, find a vector w in ℝ4 so that {**u**, **v**, **w**} is linearly independent and a non-zero vector z in ℝ4 so that {**u**, **v**, **z**} is linearly dependent:


In [101]:
u = np.array([[-2,-7,3,4]])
v = np.array([[-10,6,10,2]])

A = np.concatenate((u,v))
print(np.array(Matrix(A).nullspace())[0].T[0])
# print(A)

z = 2*u
print(z)

[44/41 5/41 1 0]
[[ -4 -14   6   8]]


## Question 3

Give a basis for span(S), where S is the set given below.

In [33]:
S = np.array([
    [0,0,2,-2],
    [1,-1,-1,3],
    [0,1,7,-9]
])

Matrix(np.eye(np.linalg.matrix_rank(S),dtype=int))

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## Question 4

 Give a basis for the image of the matrix A.

In [72]:
S = np.array([
    [2,2,-2,-2],
    [-3,-3,6,6],
    [-2,-1,0,-2]
])

img = Matrix(S).columnspace()

print(f'Number of vectors = {len(img)}\n')
for i in range(len(img)):
    print(np.array(img)[i],'\n')


Number of vectors = 3

[[2]
 [-3]
 [-2]] 

[[2]
 [-3]
 [-1]] 

[[-2]
 [6]
 [0]] 



## Question 5

Give a basis for the null space of the matrix A.

In [89]:
A = np.array([
    [1,5,-5,0],
    [0,0,0,1],
    [0,0,0,0]
])

nullspace = Matrix(A).nullspace()

print(f'Number of vectors = {len(nullspace)}\n')
for i in range(len(nullspace)):
    print(np.array(nullspace)[i],'\n')

Number of vectors = 2

[[-5]
 [1]
 [0]
 [0]] 

[[5]
 [0]
 [1]
 [0]] 



## Question 6   

Find a basis for the eigenspace of A corresponding to the eigenvalue λ.

In [100]:
A = np.array([
    [-2,-9,-9],
    [0,-5,-4],
    [0,6,5]
])

λ = -1

eigenspace = Matrix((A - λ*np.eye(np.shape(A)[0],dtype=int))).nullspace()


print(f'Number of vectors = {len(eigenspace)}\n')
for i in range(len(eigenspace)):
    print(np.array(eigenspace)[i],'\n')


Number of vectors = 1

[[0]
 [-1]
 [1]] 

