In [1]:
import numpy as np
from sympy import *
from termcolor import colored

In [2]:
# Functions for problems

def nodiag_view(a):
    m = a.shape[0]
    p,q = a.strides
    return np.lib.stride_tricks.as_strided(a[:,1:], (m-1,m), (p+q,q))

def isOrthogonal(A,normalized=False):
    Q,R = np.linalg.qr(A)
    R = np.array(R,dtype=int)
    print(f'R from QR decomp should be diagonal, i.e.,\n{R}')
    orthog_set = (nodiag_view(R)==0).all()
    print(f'\nIs R diagonal (and full rank)? {orthog_set}\n')
    if orthog_set == True and np.linalg.matrix_rank(R) == np.shape(A[2]):
        print(colored('{u,v,w} is orthogonal\n','green'))
        if normalized:
            print(colored(f"normalized  ↓ \n{np.array(Q)}",'green'))
        print('\n','-'*20,'\n')
    else:
        print(colored('{u,v,w} is not orthogonal\n','red'))
        notOrthogonal(A)

def notOrthogonal(A):
    u,v,w =A[:,0], A[:,1],A[:,2]
    if not u@v == 0:
        print(colored(f'u@v = {u@v}','red'))
    elif not u@w == 0:
        print(colored(f'u@w = {u@w}','red'))
    elif not v@w == 0:
        print(colored(f'v@w = {v@w}','red'))

    print('\n','-'*20,'\n')

## Question 1

For each of the following sets of vectors, determine whether or not the set is orthogonal. If it is not orthogonal, show this by giving the dot product of an appropriate pair of the vectors.

In [3]:
A = np.array([
    [2,0,-1],
    [-5,11,1],
    [-4,-16,1]
])

isOrthogonal(A)

B = np.array([
    [3,1,1],
    [-2,4,1],
    [-1,-5,1]
])

isOrthogonal(B)
    


R from QR decomp should be diagonal, i.e.,
[[ -6  -1   1]
 [  0 -19   0]
 [  0   0   0]]

Is R diagonal (and full rank)? False

{u,v,w} is not orthogonal

u@v = 9

 -------------------- 

R from QR decomp should be diagonal, i.e.,
[[-3  0  0]
 [ 0 -6  0]
 [ 0  0  1]]

Is R diagonal (and full rank)? True

{u,v,w} is orthogonal


 -------------------- 



## Question 2

For each of the following sets of vectors, determine whether or not the set is orthogonal.

if the set is orthogonal, normalize it to obtain an orthonormal set

if the set is not orthogonal, show this by giving the dot product of an appropriate pair of the vectors


In [4]:
A = np.array([
    [1,4,-1],
    [-2,-1,-2],
    [-3,2,1]
])

isOrthogonal(A,normalized=True)

B = np.array([
    [-9,14,-4],
    [8,27,3],
    [18,-5,5]
])

isOrthogonal(B,normalized=True)

R from QR decomp should be diagonal, i.e.,
[[-3  0  0]
 [ 0 -4  0]
 [ 0  0  2]]

Is R diagonal (and full rank)? True

{u,v,w} is orthogonal

normalized  ↓ 
[[-0.26726124 -0.87287156 -0.40824829]
 [ 0.53452248  0.21821789 -0.81649658]
 [ 0.80178373 -0.43643578  0.40824829]]

 -------------------- 

R from QR decomp should be diagonal, i.e.,
[[ 21   0   6]
 [  0 -30   0]
 [  0   0  -1]]

Is R diagonal (and full rank)? False

{u,v,w} is not orthogonal

u@w = 150

 -------------------- 



In [5]:
 # Q matrix, but easier to read, input orthogonal set (eithr A or B)
 Matrix(A).QRdecomposition()[0]


Matrix([
[   sqrt(14)/14, 4*sqrt(21)/21, -sqrt(6)/6],
[   -sqrt(14)/7,  -sqrt(21)/21, -sqrt(6)/3],
[-3*sqrt(14)/14, 2*sqrt(21)/21,  sqrt(6)/6]])